server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
# gateway는 이름이 굳이 필요하지는 않음
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: 1st-service-get
#          uri: http://localhost:52149/
          uri: lb://1ST-SERVICE
          predicates:
            - Path=/first-service/**
          filters:
            - RewritePath=/first-service/(?<segment>.*), /$\{segment}
            - AddRequestHeader=first-request, first-request-header    # 전
            - AddResponseHeader=first-response, first-response-header # 후

        - id: 2nd-service-get
#          uri: http://localhost:51899/
          uri: lb://2ND-SERVICE
          predicates:
            - Path=/second-service/**
          filters:
            - RewritePath=/second-service/(?<segment>.*), /$\{segment}

        - id: user-service-post
          uri: lb://SWCAMP-USER-SERVICE
          predicates:
            - Path=/user-service/**
            - Method=POST
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: user-service-get
          uri: lb://SWCAMP-USER-SERVICE
          predicates:
            - Path=/user-service/**
            - Method=GET
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: order-service-get
          uri: lb://SWCAMP-ORDER-SERVICE
          predicates:
            - Path=/order-service/**
            - Method=GET
          filters:
            - RewritePath=/order-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

token:
  expiration_time: 43200000
  secret: +6HQ06S82uGTBwNXZtOcnsgXAihPT2HsVx7jTTgkd8zrusd05jHOYWhz5htMNE7s0xlxl8CFmMssH/u6dMN9sg==
